import uuid
from enum import Enum
from typing import Dict, Any, List, Optional

class TaskStatus(Enum):
    PENDING = "pending"
    ASSIGNED = "assigned"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    REVIEW = "review"
    COMPLETED = "completed"
    ARCHIVED = "archived"

class Task:
    """
    Represents a unit of work emitted by an event.
    Roles are stateless; they operate on a Task, utilizing injected Context to produce Artifacts.
    """
    def __init__(self, name: str, description: str, capability_id: str):
        self.id = str(uuid.uuid4())
        self.name = name
        self.description = description
        self.capability_id = capability_id
        self.status = TaskStatus.PENDING
        
        # Memory and inputs specific to this task
        self.context: Dict[str, Any] = {}
        # Output references generated by this task
        self.artifacts: List[str] = []

    def __repr__(self):
        return f"<Task {self.name} [{self.status.value}]>"

class TaskEngine:
    """
    Manages the lifecycle of tasks across the Continuum runtime.
    Replaces static role orchestration with a dynamic, event-driven queue.
    """
    def __init__(self):
        self.queue: List[Task] = []
        self.history: List[Task] = []
        
    def create_task(self, name: str, description: str, capability_id: str) -> Task:
        """Emits a new task into the runtime queue."""
        task = Task(name, description, capability_id)
        self.queue.append(task)
        return task
        
    def claim_task(self, task_id: str, role_id: str) -> Task:
        """A role claims a task from the queue, injecting its state."""
        for task in self.queue:
            if task.id == task_id:
                task.status = TaskStatus.IN_PROGRESS
                task.context["assigned_to"] = role_id
                return task
        raise ValueError(f"Task {task_id} not found in queue.")
        
    def complete_task(self, task_id: str, artifact_ids: List[str]) -> Task:
        """Marks a task as completed and archives it to history with its generated artifacts."""
        for task in self.queue:
            if task.id == task_id:
                task.status = TaskStatus.COMPLETED
                task.artifacts.extend(artifact_ids)
                self.queue.remove(task)
                self.history.append(task)
                return task
        raise ValueError(f"Task {task_id} not found in queue.")
