import os
import uuid
import json
import datetime
from typing import Any, Dict

class ArtifactStore:
    """
    Handles the persistence of all outputs generated by Tasks and Roles.
    Artifacts are the most important objects in the system: they represent actual work.
    """
    def __init__(self, workspace_dir: str = "."):
        self.artifacts_dir = os.path.join(workspace_dir, ".artifacts")
        os.makedirs(self.artifacts_dir, exist_ok=True)
        
    def save_artifact(self, name: str, content: Any, metadata: Dict[str, Any] = None) -> str:
        """
        Saves a generated output (e.g., Code, Markdown, Audit) to the artifact store.
        
        Args:
            name: Human-readable name of the artifact.
            content: The actual output payload.
            metadata: Contextual data (author role, task id, timestamp, etc.)
            
        Returns:
            The unique UUID of the artifact.
        """
        artifact_id = str(uuid.uuid4())
        metadata = metadata or {}
        metadata["created_at"] = datetime.datetime.now().isoformat()
        
        artifact_data = {
            "id": artifact_id,
            "name": name,
            "content": content,
            "metadata": metadata
        }
        
        file_path = os.path.join(self.artifacts_dir, f"{artifact_id}.json")
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(artifact_data, f, indent=2, ensure_ascii=False)
            
        return artifact_id
        
    def load_artifact(self, artifact_id: str) -> Dict[str, Any]:
        """Retrieves an artifact by its UUID."""
        file_path = os.path.join(self.artifacts_dir, f"{artifact_id}.json")
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Artifact {artifact_id} not found in {self.artifacts_dir}.")
            
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
